Repository FINAL-TEAM4/itoxi-be, pull requests merged in 2023-10, with the labels that each got.

#147 [#146] refactor : 권한 추가 및 에러 픽스
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/controller/PointChallengeController.java
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/dto/request/WritePointChallengePostRequest.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/controller/PetTalkPostController.java
  src/main/java/com/itoxi/petnuri/global/scheduler/EventChallengeScheduler.java
  src/main/java/com/itoxi/petnuri/global/security/jwt/JwtTokenProvider.java
Labels: refactor

#150 [#149] feat : 인기순 조회를 위한 View 테이블 생성
  src/main/java/com/itoxi/petnuri/domain/petTalk/entity/PetTalkView.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/repository/PetTalkJpaRepository.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/repository/PetTalkJpaRepositoryCustom.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/repository/PetTalkRepository.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/repository/PetTalkViewJpaRepository.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/repository/impl/PetTalkJpaRepositoryCustomImpl.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/service/PetTalkService.java
Labels: feat

#151 [#148] 데일리 인증글 작성 시 시큐리티 필터 적용
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/controller/DailyAuthController.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/repository/DailyChallengeRepositoryImpl.java
Labels: refactor

#172 [#169] refactor: 포인트 response 수정
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/controller/DailyAuthController.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/util/QuerydslDateTimeFormatter.java
  src/main/java/com/itoxi/petnuri/domain/point/controller/PointController.java
  src/main/java/com/itoxi/petnuri/domain/point/dto/response/PointResponse.java
  src/main/java/com/itoxi/petnuri/domain/point/repository/PointRepositoryImpl.java
  src/test/java/com/itoxi/petnuri/domain/point/repository/PointRepositoryImplTest.java
Labels: refactor

#173 [#170] feat : 포인트 챌린지 및 스케쥴링 기능 개선
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/controller/PointChallengeController.java
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/dto/response/LoadPointChallengePostDetailsResponse.java
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/entity/PointChallenge.java
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/repository/PointChallengeRepository.java
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/repository/PointChallengeRewardJpaRepository.java
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/service/PointChallengeService.java
  src/main/java/com/itoxi/petnuri/global/scheduler/EventChallengeScheduler.java
  src/main/resources/table/h2/schema.sql
Labels: fix, feat, refactor

#187 [#186] fix: 펫 대표 프로필 수정 시 대표 프로필 지정 버튼을 누르지 않아도 대표 프로필로 지정
  src/main/java/com/itoxi/petnuri/domain/member/service/MemberService.java
Labels: fix

#191 fix : 카카오 client secret key 삭제
  src/main/java/com/itoxi/petnuri/domain/member/service/AuthService.java
Labels: fix

#192 [#190] refactor : 카카오 login 리팩토링
  src/main/java/com/itoxi/petnuri/domain/member/service/AuthService.java
Labels: refactor

#194 [#193] fix : 회원탈퇴 시 펫톡 관련 삭제 로직 추가
  src/main/java/com/itoxi/petnuri/domain/member/service/MemberService.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/repository/PetTalkEmotionRepository.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/repository/PetTalkPhotoJpaRepository.java
Labels: fix
