Repository FINAL-TEAM4/itoxi-be, pull requests merged in 2023-09, with the labels that each got.

#6 Feat/#4 member entity 생성
  src/main/java/com/itoxi/petnuri/domain/member/entity/Member.java
  src/main/java/com/itoxi/petnuri/domain/member/type/MemberProvider.java
  src/main/java/com/itoxi/petnuri/domain/member/type/MemberRole.java
Labels: feat

#5 Feature/#3 pet entity
  src/main/java/com/itoxi/petnuri/domain/petTalk/entity/Pet.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/type/PetGender.java
Labels: feat

#13 [#7]feat: Daily challenge entity 생성
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/DailyAuth.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/DailyChallenge.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/DailyParticipate.java
Labels: feat

#9 Feature/#8 pettalk Reply, Like Entity 설정
  src/main/java/com/itoxi/petnuri/domain/petTalk/entity/PetTalkLike.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/entity/PetTalkReply.java
Labels: feat

#20 [#18] Feat: Point 관련 entity 생성
  src/main/java/com/itoxi/petnuri/domain/point/entity/GetPoint.java
  src/main/java/com/itoxi/petnuri/domain/point/entity/Point.java
  src/main/java/com/itoxi/petnuri/domain/point/entity/UsePoint.java
Labels: feat

#19 [#17] Refactor: Daily challenge 관련 entity 수정
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/entity/DailyAuth.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/entity/DailyChallenge.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/entity/DailyParticipate.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/type/ChallengeStatus.java
Labels: refactor

#32 [#16] feat : security, jwt 설정
  build.gradle
  src/main/java/com/itoxi/petnuri/global/error/ErrorMessage.java
  src/main/java/com/itoxi/petnuri/global/error/MyExceptionHandler.java
  src/main/java/com/itoxi/petnuri/global/error/MyValidationHandler.java
  src/main/java/com/itoxi/petnuri/global/error/exception/Exception400.java
  src/main/java/com/itoxi/petnuri/global/error/exception/Exception401.java
  src/main/java/com/itoxi/petnuri/global/error/exception/Exception403.java
  src/main/java/com/itoxi/petnuri/global/error/exception/Exception404.java
  src/main/java/com/itoxi/petnuri/global/error/exception/Exception500.java
  src/main/java/com/itoxi/petnuri/global/error/exception/ValidationException.java
  src/main/java/com/itoxi/petnuri/global/redis/RedisConfig.java
  src/main/java/com/itoxi/petnuri/global/redis/RedisService.java
  src/main/java/com/itoxi/petnuri/global/security/SecurityConfig.java
  src/main/java/com/itoxi/petnuri/global/security/auth/PrincipalDetails.java
  src/main/java/com/itoxi/petnuri/global/security/auth/PrincipalDetailsService.java
  src/main/java/com/itoxi/petnuri/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/itoxi/petnuri/global/security/jwt/JwtExceptionFilter.java
  src/main/java/com/itoxi/petnuri/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/itoxi/petnuri/global/util/ApiResponse.java
  src/main/java/com/itoxi/petnuri/global/util/CookieUtil.java
  src/main/java/com/itoxi/petnuri/global/util/FilterResponse.java
  src/main/java/com/itoxi/petnuri/global/util/JsonConverter.java
  src/main/resources/application-api.yml
  src/main/resources/application.yml
Labels: feat

#44 [#43] fix : member 엔티티 수정, 더미데이터 수정
  src/main/java/com/itoxi/petnuri/domain/member/entity/Member.java
  src/main/resources/table/h2/data.sql
  src/main/resources/table/h2/schema.sql
Labels: fix

#46 [#15] refactor: kakao 리다이렉트 주소 수정 및 디렉토리 구조 변경
  src/main/java/com/itoxi/petnuri/domain/member/controller/AuthController.java
  src/main/java/com/itoxi/petnuri/domain/member/dto/response/KakaoInfo.java
  src/main/java/com/itoxi/petnuri/domain/member/dto/response/KakaoToken.java
  src/main/java/com/itoxi/petnuri/domain/member/dto/response/LoginResDto.java
  src/main/java/com/itoxi/petnuri/domain/member/service/AuthService.java
Labels: refactor

#45 [#11] fix: point 테스트용 DailyChallengeRepository
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/entity/DailyChallenge.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/entity/DailyParticipate.java
  src/main/java/com/itoxi/petnuri/domain/dailychallenge/repository/DailyChallengeRepository.java
Labels: fix

#55 [#53] feat : mypage 프로필 수정 기능 구현
  src/main/java/com/itoxi/petnuri/domain/member/controller/MemberController.java
  src/main/java/com/itoxi/petnuri/domain/member/dto/request/ProfileUpdateReq.java
  src/main/java/com/itoxi/petnuri/domain/member/dto/response/MyPageResp.java
  src/main/java/com/itoxi/petnuri/domain/member/dto/response/ProfileUpdateResp.java
  src/main/java/com/itoxi/petnuri/domain/member/service/MemberService.java
  src/main/java/com/itoxi/petnuri/global/s3/service/AmazonS3Service.java
Labels: feat

#67 [#66] feat: 배송/상품 entity,dummy data 생성
  src/main/java/com/itoxi/petnuri/domain/delivery/entity/ChallengeDelivery.java
  src/main/java/com/itoxi/petnuri/domain/delivery/entity/DeliveryAddress.java
  src/main/java/com/itoxi/petnuri/domain/delivery/type/DeliveryProcess.java
  src/main/java/com/itoxi/petnuri/domain/product/entity/ChallengeProduct.java
  src/main/java/com/itoxi/petnuri/domain/product/entity/Product.java
  src/main/java/com/itoxi/petnuri/domain/product/type/ChallengeProductCategory.java
  src/main/java/com/itoxi/petnuri/domain/product/type/ProductCategory.java
  src/main/resources/table/h2/data.sql
  src/main/resources/table/h2/schema.sql
Labels: feat

#70 [#57] fix: 댓글 등록 시 replyCount 업데이트
  src/main/java/com/itoxi/petnuri/domain/petTalk/entity/PetTalk.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/repository/PetTalkRepository.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/service/PetTalkEmotionService.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/service/PetTalkReplyService.java
Labels: fix

#87 [#86] feat : 도커 관련 파일 생성
  Dockerfile
  docker-folder/Dockerfile
  docker-folder/docker-compose.yml
Labels: feat

#88 [#82] feat: 대표 프로필 지정 기능
  src/main/java/com/itoxi/petnuri/domain/member/controller/MemberController.java
  src/main/java/com/itoxi/petnuri/domain/member/dto/request/PetProfileReq.java
  src/main/java/com/itoxi/petnuri/domain/member/entity/Pet.java
  src/main/java/com/itoxi/petnuri/domain/member/service/MemberService.java
  src/main/java/com/itoxi/petnuri/global/common/exception/type/ErrorCode.java
Labels: feat

#95 [#94] refactor: security 접근 권한 방법 리팩토링
  src/main/java/com/itoxi/petnuri/global/security/SecurityConfig.java
Labels: refactor

#100 refactor: DeliveryAddressRepository 반환 값 변경으로 인한 코드 수정
  src/main/java/com/itoxi/petnuri/domain/delivery/dto/response/DeliveryListRes.java
  src/main/java/com/itoxi/petnuri/domain/delivery/repository/DeliveryAddressRepository.java
  src/main/java/com/itoxi/petnuri/domain/delivery/service/DeliveryService.java
Labels: refactor

#109 [#108] refactor : security Exception 주석 처리
  src/main/java/com/itoxi/petnuri/global/config/SecurityConfig.java
Labels: refactor

#111 [#110] feat : 테스트를 위한 회원 가데이터 생성
  src/main/java/com/itoxi/petnuri/domain/eventChallenge/service/PointChallengeReviewService.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/service/PetTalkService.java
Labels: feat

#122 [#119] refactor: petGender 라벨 추가
  src/main/java/com/itoxi/petnuri/domain/member/dto/request/PetProfileReq.java
  src/main/java/com/itoxi/petnuri/domain/member/dto/request/PetSaveReq.java
  src/main/java/com/itoxi/petnuri/domain/member/entity/Pet.java
  src/main/java/com/itoxi/petnuri/domain/member/service/MemberService.java
  src/main/java/com/itoxi/petnuri/domain/petTalk/type/PetGender.java
  src/main/java/com/itoxi/petnuri/global/common/exception/type/ErrorCode.java
Labels: refactor

#124 [#123] Refactor : 펫 성별 라벨 적용
  src/main/java/com/itoxi/petnuri/domain/member/dto/response/MainResp.java
Labels: refactor
